In [ ]:
###Libraries used TensorFlow> 2.0 and keras

In [1]:
##to implement the one-hot process
from keras.preprocessing.text import one_hot

In [2]:
#tensorflow>2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
###sentences
sent =['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good girl',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good girl',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
###Vocabulary size
voc_size = 10000

In [6]:
###One-Hot representation
onehot_repr=[one_hot(words, voc_size)for words in sent]
print(onehot_repr)

[[7260, 8407, 6439, 6887], [7260, 8407, 6439, 956], [7260, 5041, 6439, 9017], [6036, 3246, 9713, 5109, 1293], [6036, 3246, 9713, 5109, 8447], [4608, 7260, 6857, 6439, 606], [7964, 5576, 2592, 5109]]


In [7]:
##Word Embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [11]:
sent_length =8
embedded_docs=pad_sequences(onehot_repr, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7260 8407 6439 6887]
 [   0    0    0    0 7260 8407 6439  956]
 [   0    0    0    0 7260 5041 6439 9017]
 [   0    0    0 6036 3246 9713 5109 1293]
 [   0    0    0 6036 3246 9713 5109 8447]
 [   0    0    0 4608 7260 6857 6439  606]
 [   0    0    0    0 7964 5576 2592 5109]]


In [12]:
dim = 15

In [13]:
model=Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 210ms/step
[[[-0.04991039  0.0329578  -0.049846   -0.03319844 -0.03067362
    0.00279454 -0.00275932  0.03659563 -0.00157131 -0.01937804]
  [-0.04991039  0.0329578  -0.049846   -0.03319844 -0.03067362
    0.00279454 -0.00275932  0.03659563 -0.00157131 -0.01937804]
  [-0.04991039  0.0329578  -0.049846   -0.03319844 -0.03067362
    0.00279454 -0.00275932  0.03659563 -0.00157131 -0.01937804]
  [-0.04991039  0.0329578  -0.049846   -0.03319844 -0.03067362
    0.00279454 -0.00275932  0.03659563 -0.00157131 -0.01937804]
  [ 0.03757003  0.02744826 -0.02921709 -0.0227682  -0.04256122
   -0.00419787 -0.00031637  0.04866515 -0.00315885  0.03083595]
  [-0.02163298 -0.00354487 -0.03157129  0.00192925  0.00333063
   -0.0397895  -0.01178374 -0.01940836 -0.03950157  0.01901061]
  [-0.03044872 -0.01496614 -0.04107845 -0.0291112   0.0108401
    0.03184991 -0.02296311 -0.03180379  0.03027303 -0.00362336]
  [ 0.02246194  0.0230956  -0.03074476  0.02097556  0.03016

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 7260, 8407, 6439, 6887])

In [17]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 21ms/step
[[-0.04991039  0.0329578  -0.049846   -0.03319844 -0.03067362  0.00279454
  -0.00275932  0.03659563 -0.00157131 -0.01937804]
 [-0.04991039  0.0329578  -0.049846   -0.03319844 -0.03067362  0.00279454
  -0.00275932  0.03659563 -0.00157131 -0.01937804]
 [-0.04991039  0.0329578  -0.049846   -0.03319844 -0.03067362  0.00279454
  -0.00275932  0.03659563 -0.00157131 -0.01937804]
 [-0.04991039  0.0329578  -0.049846   -0.03319844 -0.03067362  0.00279454
  -0.00275932  0.03659563 -0.00157131 -0.01937804]
 [ 0.03757003  0.02744826 -0.02921709 -0.0227682  -0.04256122 -0.00419787
  -0.00031637  0.04866515 -0.00315885  0.03083595]
 [-0.02163298 -0.00354487 -0.03157129  0.00192925  0.00333063 -0.0397895
  -0.01178374 -0.01940836 -0.03950157  0.01901061]
 [-0.03044872 -0.01496614 -0.04107845 -0.0291112   0.0108401   0.03184991
  -0.02296311 -0.03180379  0.03027303 -0.00362336]
 [ 0.02246194  0.0230956  -0.03074476  0.02097556  0.03016079  0.03010288
